### ISSUE TITLE
The tests are not actually being run on Travis, and many fail.

### ISSUE THREAD

**Issue by danielballan** [scikit-beam/scikit-beam#485]
This helps explain why the bug in #482 was not caught. The .travis.yml has a [bash error in the section that is supposed to run the tests](https://travis-ci.org/scikit-beam/scikit-beam/jobs/191025048#L882), but it still exits with exit status 0, so we Travis reports success. I might be wrong, but it looks like this problem has been around for [almost a year](https://github.com/scikit-beam/scikit-beam/pull/416/files). I will investigate more later.

**Comment by sameera2004** [comment]
@danielballan big list is created by
ERROR: skbeam.core.accumulators.tests.test_histogram.test_1d_histogram([10, 0, 10.01],

TypeError: Function call with ambiguous argument types

**Comment by danielballan** [comment]
Update: There are two tests failures. (Some of the "many" failures I was originally seeing were local configuration problems.) One is fixed by #484. The other is:

```
======================================================================
ERROR: skbeam.io.tests.test_fit2d_save.test_save_output_fit2d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dallan/miniconda/envs/bnl/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/dallan/Documents/Repos/scikit-beam/skbeam/io/tests/test_fit2d_save.py", line 56, in test_save_output_fit2d
    msk2 = read_fit2d_msk(filename)
  File "/Users/dallan/Documents/Repos/scikit-beam/skbeam/io/fit2d.py", line 38, in read_fit2d_msk
    a = fabio.open(filename)
  File "/Users/dallan/miniconda/envs/bnl/lib/python3.5/site-packages/fabio/openimage.py", line 152, in openimage
    obj = _openimage(filename)
  File "/Users/dallan/miniconda/envs/bnl/lib/python3.5/site-packages/fabio/openimage.py", line 203, in _openimage
    raise error
  File "/Users/dallan/miniconda/envs/bnl/lib/python3.5/site-packages/fabio/openimage.py", line 199, in _openimage
    byts = imo._open(actual_filename).read(18)
  File "/Users/dallan/miniconda/envs/bnl/lib/python3.5/site-packages/fabio/fabioimage.py", line 540, in _open
    fileObject = fabioutils.File(fname, mode)
  File "/Users/dallan/miniconda/envs/bnl/lib/python3.5/site-packages/fabio/fabioutils.py", line 465, in __init__
    FileIO.__init__(self, name, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'function_values'
-------------------- >> begin captured logging << --------------------
skbeam.io.save_powder_output: INFO: Output file of diffraction intensities already exists
fabioutils: DEBUG: l242: invalid literal for int() with base 10: ''
openimage: DEBUG: Attempting to open function_values
openimage: ERROR: [Errno 2] No such file or directory: 'function_values': File probably does not exist
--------------------- >> end captured logging << ---------------------
```

@CJ-Wright Would you please look into this one? Remember that it's possible it has *never* passed if, as in #482, you were relying on Travis to run the tests.

**Comment by ericdill** [comment]
@danielballan seems like those big if blocks should be stripped out into their own bash scripts.  Looking at that travis file with fresh eyes is utterly terrifying. Want a PR that puts that stuff in different bash scripts?

**Comment by danielballan** [comment]
Is that standard practice nowadays? I find one long file easier to read/debug, but really anything that runs is fine by me.

**Comment by CJ-Wright** [comment]
@danielballan I have fixed the test for fit2d. see #486

**Comment by mrakitin** [comment]
It looks like a candidate to be closed. @danielballan, @CJ-Wright?
