### ISSUE TITLE
pip install issue?

### ISSUE THREAD

**Issue by jrmlhermitte** [scikit-beam/scikit-beam#507]
Seems to be a pip install issue.
Running this:
```
conda create -n testenv pip nose python=3.5 numpy=1.11 coverage cython flake8 scipy
source activate testenv
pip install codecov cachey pillow matplotlib distributed dask pyyaml scikit-beam
```

gives the following error:
```
Collecting scikit-beam
  Using cached scikit-beam-0.0.8.post0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c1qbo7cw/scikit-beam/setup.py", line 39, in <module>
        ext_modules=c_ext() + cython_ext(),
      File "/tmp/pip-build-c1qbo7cw/scikit-beam/setup.py", line 26, in cython_ext
        return cythonize("**/*.pyx")
      File "/home/lhermitte/conda_envs/testenv/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 818, in cythonize
        aliases=aliases)
      File "/home/lhermitte/conda_envs/testenv/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 704, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/lhermitte/conda_envs/testenv/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 108, in nonempty
        raise ValueError(error_msg)
    ValueError: '**/*.pyx' doesn't match any files
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c1qbo7cw/scikit-beam/
```

**Comment by jrmlhermitte** [comment]
I don't see this on my mac pro running mojave. Would have helped to be specific with the actual system involved. Closing for incomplete information
