### ISSUE TITLE
Documentation page is down

### ISSUE THREAD

**Issue by ambarb** [scikit-beam/scikit-beam#543]
On clicking on the documentation link
http://scikit-beam.github.io/scikit-beam/ 

There is a `Page not found error`.

**Comment by ambarb** [comment]
It seems that the examples are also broken.

**Comment by ambarb** [comment]
now it magically works -- the examples
Unsure if this is a repo issue or a GitHub infrastructure issue.

**Comment by ericdill** [comment]
Looks like the last build on Jenkins just pushed an empty repo back to the gh-pages branch (this is what serves the scikit-beam docs. @danielballan I think may have been the last person to work on that auto docs build infrastructure?

https://github.com/scikit-beam/scikit-beam/tree/gh-pages?files=1

**Comment by ericdill** [comment]
Docs are failing. travis has the following stack trace:

```
# make -C example notebooks
sphinx-build -b html -v -d _build/doctrees   . _build/html
Running Sphinx v2.1.0
making output directory... done
[autosummary] generating autosummary for: api_changes.rst, api_changes/2014-08-29-gridder.rst, api_changes/2014-09-03-gridder.rst, api_changes/2014-09-04-constants.rst, api_changes/2014-09-08_fit_quad_to_peak.rst, api_changes/2014-09-09-physics_peak.rst, api_changes/2014-09-12-physics_peak.rst, api_changes/2014-09-30-rcparams.rst, api_changes/2014-10-03-core.rst, api_changes/2014-11-12-fitting.rst, ..., resource/dev_guide/adding_files.rst, resource/dev_guide/doc_doc.rst, resource/dev_guide/git_guide.rst, resource/dev_guide/index.rst, resource/dev_guide/logging.rst, resource/dev_guide/workflow.rst, warnings.rst, whats_new.rst, whatsnew/0.5.rst, whatsnew/index.rst
[autosummary] generating autosummary for: /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.calibration.estimate_d_blind.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.calibration.refine_center.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.basic.BasicElement.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrf.XrayLibWrap.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrf.XrayLibWrap_Energy.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrf.XrfElement.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrf.emission_line_search.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrs.HKL.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrs.PowderStandard.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrs.Reflection.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.constants.xrs.calibration_standards.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.speckle.normalize_bin_edges.rst, /home/travis/repo-clone/doc/resource/api/core/_as_gen/skbeam.core.speckle.xsvs.rst, /home/travis/repo-clone/doc/resource/api/core/skbeam.core.cdi.cal_diff_error.rst, /home/travis/repo-clone/doc/resource/api/core/skbeam.core.cdi.cdi_recon.rst, /home/travis/repo-clone/doc/resource/api/core/skbeam.core.cdi.find_support.rst, /home/travis/repo-clone/doc/resource/api/core/skbeam.core.cdi.generate_box_support.rst, /home/travis/repo-clone/doc/resource/api/core/skbeam.core.cdi.generate_disk_support.rst, /home/travis/repo-clone/doc/resource/api/core/skbeam.core.cdi.generate_random_phase_field.rst, /home/travis/repo-clone/doc/resource/api/core/skbeam.core.cdi.pi_modulus.rst
loading intersphinx inventory from http://docs.python.org/3.5/objects.inv...
intersphinx inventory has moved: http://docs.python.org/3.5/objects.inv -> https://docs.python.org/3.5/objects.inv
loading intersphinx inventory from http://numpy.org/objects.inv...
intersphinx inventory has moved: http://numpy.org/objects.inv -> http://www.numpy.org/objects.inv
loading intersphinx inventory from http://matplotlib.org/objects.inv...
intersphinx inventory has moved: http://matplotlib.org/objects.inv -> https://matplotlib.org/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 89 source files that are out of date
updating environment: 110 added, 0 changed, 0 removed
reading sources... [  0%] api_changes
reading sources... [  1%] api_changes/2014-08-29-gridder
reading sources... [  2%] api_changes/2014-09-03-gridder
reading sources... [  3%] api_changes/2014-09-04-constants
reading sources... [  4%] api_changes/2014-09-08_fit_quad_to_peak
reading sources... [  5%] api_changes/2014-09-09-physics_peak
reading sources... [  6%] api_changes/2014-09-12-physics_peak
reading sources... [  7%] api_changes/2014-09-30-rcparams
reading sources... [  8%] api_changes/2014-10-03-core
reading sources... [  9%] api_changes/2014-11-12-fitting
reading sources... [ 10%] api_changes/2015-04-10-linear_spectrum_fitting
reading sources... [ 10%] api_changes/2015-04-27-core
reading sources... [ 11%] api_changes/2015-06-23-image_processing
reading sources... [ 12%] api_changes/2015-09-01-xrf_model
reading sources... [ 13%] api_changes/2015-09-16-correlation
reading sources... [ 14%] api_changes/2015-09-16-roi
reading sources... [ 15%] api_changes/2015-12-01-roi
reading sources... [ 16%] api_changes/2015-12-01-utils
reading sources... [ 17%] development/affiliated-packages
reading sources... [ 18%] development/building
reading sources... [ 19%] development/ccython
reading sources... [ 20%] development/codeguide
reading sources... [ 20%] development/codeguide_emacs
reading sources... [ 21%] development/docguide
reading sources... [ 22%] development/docrules
reading sources... [ 23%] development/releasing
reading sources... [ 24%] development/scripts
reading sources... [ 25%] development/testguide
reading sources... [ 26%] development/vision
reading sources... [ 27%] development/workflow/additional_git_topics
reading sources... [ 28%] development/workflow/command_history
reading sources... [ 29%] development/workflow/development_workflow
reading sources... [ 30%] development/workflow/get_devel_version
reading sources... [ 30%] development/workflow/git_edit_workflow_examples
reading sources... [ 31%] development/workflow/git_install
reading sources... [ 32%] development/workflow/git_resources
reading sources... [ 33%] development/workflow/maintainer_workflow
reading sources... [ 34%] development/workflow/patches
reading sources... [ 35%] development/workflow/terminal_cast
reading sources... [ 36%] development/workflow/virtual_pythons
reading sources... [ 37%] development/workflow/virtualenv_detail
reading sources... [ 38%] examples/index
reading sources... [ 39%] getting_started
reading sources... [ 40%] index
reading sources... [ 40%] install
reading sources... [ 41%] installation
reading sources... [ 42%] introduction
reading sources... [ 43%] known_issues
reading sources... [ 44%] overview
reading sources... [ 45%] python_versions
reading sources... [ 46%] resource/api/core
reading sources... [ 47%] resource/api/core/_as_gen/skbeam.core.calibration.estimate_d_blind
reading sources... [ 48%] resource/api/core/_as_gen/skbeam.core.calibration.refine_center
reading sources... [ 49%] resource/api/core/_as_gen/skbeam.core.constants.basic.BasicElement
reading sources... [ 50%] resource/api/core/_as_gen/skbeam.core.constants.xrf.XrayLibWrap
reading sources... [ 50%] resource/api/core/_as_gen/skbeam.core.constants.xrf.XrayLibWrap_Energy
reading sources... [ 51%] resource/api/core/_as_gen/skbeam.core.constants.xrf.XrfElement
reading sources... [ 52%] resource/api/core/_as_gen/skbeam.core.constants.xrf.emission_line_search
reading sources... [ 53%] resource/api/core/_as_gen/skbeam.core.constants.xrs.HKL
reading sources... [ 54%] resource/api/core/_as_gen/skbeam.core.constants.xrs.PowderStandard
reading sources... [ 55%] resource/api/core/_as_gen/skbeam.core.constants.xrs.Reflection
reading sources... [ 56%] resource/api/core/_as_gen/skbeam.core.constants.xrs.calibration_standards
reading sources... [ 57%] resource/api/core/_as_gen/skbeam.core.speckle.normalize_bin_edges
reading sources... [ 58%] resource/api/core/_as_gen/skbeam.core.speckle.xsvs
reading sources... [ 59%] resource/api/core/calibration
reading sources... [ 60%] resource/api/core/cdi
reading sources... [ 60%] resource/api/core/constants
reading sources... [ 61%] resource/api/core/correlation
/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Note in the docstring of <function angle_grid at 0x2ae4c24a0950> in /home/travis/mc/envs/testenv/lib/python3.6/site-packages/scikit_beam-0.0.15-py3.6-linux-x86_64.egg/skbeam/core/utils.py.
  warn(msg)
/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Return in the docstring of <function geometric_series at 0x2ae4c24a3048> in /home/travis/mc/envs/testenv/lib/python3.6/site-packages/scikit_beam-0.0.15-py3.6-linux-x86_64.egg/skbeam/core/utils.py.
  warn(msg)
/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Example in the docstring of <function ring_edges at 0x2ae4c24a31e0> in /home/travis/mc/envs/testenv/lib/python3.6/site-packages/scikit_beam-0.0.15-py3.6-linux-x86_64.egg/skbeam/core/roi.py.
  warn(msg)
/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Notes : in the docstring of <function auto_corr_scat_factor at 0x2ae4c63b9ea0> in /home/travis/mc/envs/testenv/lib/python3.6/site-packages/scikit_beam-0.0.15-py3.6-linux-x86_64.egg/skbeam/core/correlation.py.
  warn(msg)
/home/travis/repo-clone/doc/development/docrules.rst:367: WARNING: Footnote [1] is not referenced.
Traceback (most recent call last):
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/io.py", line 325, in read_doc
    pub.publish()
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/io.py", line 113, in read
    self.parse()
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2988, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/ext/autodoc/directive.py", line 150, in run
    documenter.generate(more_content=self.content)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 765, in generate
    self.document_members(all_members)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 686, in document_members
    check_module=members_check_module and not isattr)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 752, in generate
    sig = self.format_signature()
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 978, in format_signature
    return super().format_signature(**kwargs)  # type: ignore
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 416, in format_signature
    self.object, self.options, args, retann)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/events.py", line 112, in emit_firstresult
    for result in self.emit(name, *args):
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/numpydoc.py", line 217, in mangle_signature
    doc = get_doc_object(obj, config={'show_class_members': False})
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape_sphinx.py", line 458, in get_doc_object
    return SphinxFunctionDoc(obj, doc=doc, config=config)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape_sphinx.py", line 418, in __init__
    FunctionDoc.__init__(self, obj, doc=doc, config=config)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py", line 573, in __init__
    NumpyDocString.__init__(self, doc)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py", line 153, in __init__
    self._parse()
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py", line 408, in _parse
    self['See Also'] = self._parse_see_also(content)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py", line 330, in _parse_see_also
    raise ParseError("%s is not a item name" % line)
numpydoc.docscrape.ParseError: comments on `multi_tau_auto_corr` is not a item name in 'Generator implementation of two-time correlation\n\nIf you do not want multi-tau correlation, set num_levels to 1 and\nnum_bufs to the number of images you wish to correlate\n\nMulti-tau correlation uses a scheme to achieve long-time correlations\ninexpensively by downsampling the data, iteratively combining successive\nframes.\n\nThe longest lag time computed is ``num_levels * num_bufs``.\n\nSee Also\n--------\ncomments on `multi_tau_auto_corr`\n\nParameters\n----------\nlabels : array\n    labeled array of the same shape as the image stack;\n    each ROI is represented by a distinct label (i.e., integer)\nimages : iterable of 2D arrays\n    dimensions are: (rr, cc), iterable of 2D arrays\nnum_frames : int\n    number of images to use\n    default is number of images\nnum_bufs : int, must be even\n    maximum lag step to compute in each generation of\n    downsampling\nnum_levels : int, optional\n    how many generations of downsampling to perform, i.e.,\n    the depth of the binomial tree of averaged frames\n    default is one\n\nYields\n------\nnamedtuple\n    A ``results`` object is yielded after every image has been processed.\n    This `reults` object contains, in this order:\n\n    - ``g2``: the normalized correlation\n      shape is (num_rois, len(lag_steps), len(lag_steps))\n    - ``lag_steps``: the times at which the correlation was computed\n    - ``_internal_state``: all of the internal state. Can be passed back in\n      to ``lazy_one_time`` as the ``internal_state`` parameter\n\nNotes\n-----\nThe two-time correlation function is defined as\n\n.. math::\n    C(q,t_1,t_2) = \\frac{<I(q,t_1)I(q,t_2)>}{<I(q, t_1)><I(q,t_2)>}\n\nHere, the ensemble averages are performed over many pixels of detector,\nall having the same ``q`` value. The average time or age is equal to\n``(t1+t2)/2``, measured by the distance along the ``t1 = t2`` diagonal.\nThe time difference ``t = |t1 - t2|``, with is distance from the\n``t1 = t2`` diagonal in the perpendicular direction.\nIn the equilibrium system, the two-time correlation functions depend only\non the time difference ``t``, and hence the two-time correlation contour\nlines are parallel.\n\n[1]_\n\nReferences\n----------\n\n.. [1] A. Fluerasu, A. Moussaid, A. Mandsen and A. Schofield,\n   "Slow dynamics and aging in collodial gels studied by x-ray\n   photon correlation spectroscopy," Phys. Rev. E., vol 76, p\n   010401(1-4), 2007.'
Exception occurred:
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpydoc/docscrape.py", line 330, in _parse_see_also
    raise ParseError("%s is not a item name" % line)
numpydoc.docscrape.ParseError: comments on `multi_tau_auto_corr` is not a item name in 'Generator implementation of two-time correlation\n\nIf you do not want multi-tau correlation, set num_levels to 1 and\nnum_bufs to the number of images you wish to correlate\n\nMulti-tau correlation uses a scheme to achieve long-time correlations\ninexpensively by downsampling the data, iteratively combining successive\nframes.\n\nThe longest lag time computed is ``num_levels * num_bufs``.\n\nSee Also\n--------\ncomments on `multi_tau_auto_corr`\n\nParameters\n----------\nlabels : array\n    labeled array of the same shape as the image stack;\n    each ROI is represented by a distinct label (i.e., integer)\nimages : iterable of 2D arrays\n    dimensions are: (rr, cc), iterable of 2D arrays\nnum_frames : int\n    number of images to use\n    default is number of images\nnum_bufs : int, must be even\n    maximum lag step to compute in each generation of\n    downsampling\nnum_levels : int, optional\n    how many generations of downsampling to perform, i.e.,\n    the depth of the binomial tree of averaged frames\n    default is one\n\nYields\n------\nnamedtuple\n    A ``results`` object is yielded after every image has been processed.\n    This `reults` object contains, in this order:\n\n    - ``g2``: the normalized correlation\n      shape is (num_rois, len(lag_steps), len(lag_steps))\n    - ``lag_steps``: the times at which the correlation was computed\n    - ``_internal_state``: all of the internal state. Can be passed back in\n      to ``lazy_one_time`` as the ``internal_state`` parameter\n\nNotes\n-----\nThe two-time correlation function is defined as\n\n.. math::\n    C(q,t_1,t_2) = \\frac{<I(q,t_1)I(q,t_2)>}{<I(q, t_1)><I(q,t_2)>}\n\nHere, the ensemble averages are performed over many pixels of detector,\nall having the same ``q`` value. The average time or age is equal to\n``(t1+t2)/2``, measured by the distance along the ``t1 = t2`` diagonal.\nThe time difference ``t = |t1 - t2|``, with is distance from the\n``t1 = t2`` diagonal in the perpendicular direction.\nIn the equilibrium system, the two-time correlation functions depend only\non the time difference ``t``, and hence the two-time correlation contour\nlines are parallel.\n\n[1]_\n\nReferences\n----------\n\n.. [1] A. Fluerasu, A. Moussaid, A. Mandsen and A. Schofield,\n   "Slow dynamics and aging in collodial gels studied by x-ray\n   photon correlation spectroscopy," Phys. Rev. E., vol 76, p\n   010401(1-4), 2007.'
The full traceback has been saved in /tmp/sphinx-err-ccw3imdx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

**Comment by ericdill** [comment]
Docs are fixed per #544

**Comment by ericdill** [comment]
Thanks for the report @ambarb

**Comment by ambarb** [comment]
@ericdill thanks for looking into it
